FORMAT: 1A
HOST: https://www.sysuactivity.com/api

# SYSU-ActivityPlusPC-API

SYSU-ActivityPlusPC is a web application for SYSU clubs and organizations to pulish and manage their activitys.

## Session Collection [/session]

### PC User Login [POST /session]

You may sign in using this action.

+ Request (application/json)
    
    + Headers

            Authorization: token_string

    + Body

            {
                "account": "用户名",
                "password": "加密后的密码"
            }

+ Response 200 (application/json)

            {
                "id": 21,
                "name": "组织名称",
                "logo": "组织logo文件名",
                "token": "token_string"
            }
    
+ Response 204
+ Response 400

## PC User Collection [/pcusers]

### PC User Sign up [POST /pcusers]

You may sign up using this action.

+ Request (application/json)

    + Body

            {
                "name": "组织名称",
                "email": "联系邮箱",
                "logo": "组织logo文件名",
                "evidence": "身份证明文件名",
                "info": "备注信息"
            }

+ Response 200
+ Response 400

## Picture Collection [/images]

### Upload a picture [POST /images]

You may upload a picture to server using this action.

+ Request (multipart/form-data)

            图片的multipartfile
        
+ Response 200 (application/json)

            {
                "filename": "上传的文件的加密后的文件名"
            }

+ Response 400

## Activity Collection [/act]

### Publish a New Activity [POST /act]

You may publish a new activity using this action. It takes a JSON
object containing a activity information expect 'id' in the
form of choices.

+ Request (application/json)

        {
                "name": "sample",
                "startTime": "2017-09-01",
                "endTime": "2017-09-02",
                "location":"三饭小广场",
                "campus":1,
                "enrollCondition":"计算机学院全体学生",
                "sponsor":"SDCS团委",
                "type":2,
                "pubStartTime": "2017-09-01",
                "pubEndTime": "2017-09-02",
                "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
                "canEnrolled":null,
                "email":null,
                "enrollWay":null,
                "enrollEndTime":null,
                "reward":null,
                "introduction":null,
                "requirement":null,
                "poster":null,
                "club":null,
                "qrcode":null
        }

+ Response 200

+ Response 204

### List required activities [GET /act?page={pageNum}&verify={verified}]
List activities with the given page number.

+ Parameters
    + pageNum: `2` (number, optional) - Specified the page number
        + Default: `1`
    
    + verified: `1` (number, required) - Specified these activities selected are verified or not
    
+ Response 200 (application/json)

        {
            "content": [
                {
                    "id": 21,
                    "name": "sample",
                    "startTime": 1521594000000,
                    "endTime":1521709200000,
                    "campus":0b0001,
                    "enrollCondition":"计算机学院全体学生",
                    "sponsor":"SDCS团委",
                    "pubStartTime":1520438400000,
                    "pubEndTime":1521475200000,
                    "verified":0b01
                }
            ]
        }

+ Response 204

### Get detailed activity information [GET /act/{id}]
Get activity information with the given id no matter this activity verified or not.

+ Parameters
    + id: `9421` (number, required) - Specified the activity number
    
+ Response 200 (application/json)

        {
                "id": 21,
                "name": "sample",
                "startTime": 1521594000000,
                "endTime":1521709200000,
                "location":"三饭小广场",
                "campus":0b0001,
                "enrollCondition":"计算机学院全体学生",
                "sponsor":"SDCS团委",
                "type":2,
                "pubStartTime":1520438400000,
                "pubEndTime":1521475200000,
                "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
                "verified":0b01,
                "canEnrolled":null,
                "email":null,
                "enrollWay":null,
                "enrollEndTime":null,
                "reward":null,
                "introduction":null,
                "requirement":null,
                "poster":null,
                "club":null,
                "qrcode":null
        }
    

+ Response 204

### Modify Activity Info By Manager[POST /act/{actId}]

You may modify activity using this action. It takes a JSON
object containing a activity information expect 'id' in the
form of choices.

+ Parameters
    + actId: `9421` (number, required) - Specified the activity id you modified
    
+ Request (application/json)

        {
                "name": "sample",
                "startTime": "2017-09-01",
                "endTime": "2017-09-02",
                "location":"三饭小广场",
                "campus":1,
                "enrollCondition":"计算机学院全体学生",
                "sponsor":"SDCS团委",
                "type":2,
                "pubStartTime": "2017-09-01",
                "pubEndTime": "2017-09-02",
                "detail":"飞扬C调是计算机学院的传统活动，2018年即将迎来第11个年头；往届比赛中，无数的歌声给我们带来了很多的精彩回忆！Coding&Singing，一起来吧！",
                "canEnrolled":null,
                "email":null,
                "enrollWay":null,
                "enrollEndTime":null,
                "reward":null,
                "introduction":null,
                "requirement":null,
                "poster":null,
                "club":null,
                "qrcode":null
        }

+ Response 200

+ Response 400

### Delete Activity By Manager[DELETE /act/{actId}]
You may delete activity using this action.

+ Parameters
    + actId: `9421` (number, required) - Specified the activity id you modified
    
+ Response 200

+ Response 204

### Audit Activity By Manager[PUT /act?act={actId}&verify={verified}]

You may audit activity using this action.

+ Parameters
    + actId: `9421` (number, required) - Specified the activity id you audit
    
    + verified: `1` (number, required) - Specified pass or nopass this activity

+ Response 200

+ Response 204